syntax match Comment	"\v#[^\n]*"
syntax match Operator	"\v[\+\-\*\/\^\=\@\:]"
syntax match Type		"\v[\[\]\~]"
"syntax match Symbol	"\v\*[^ \n]+"
"syntax match Symbol	"\v[a-zA-Z0-9_\.]+"
syntax match Constant	"\v(file|EOL|SP|TAB|BS|EOF)(\n|[^a-z])"
syntax match Number		"\v[\+\-]?[0-9]+(\.[0-9]+)?([eE][\+\-]?[0-9]+)?"
syntax match Number		"\v0x[0-9a-fA-F]+"
syntax match Number		"\v0b[01]+"
syntax region String	start="'" end="'"
